/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#dfe2eb",
        "tertiary-fixed": "#dae3ee",
        "primary-fixed": "#ffddb0",
        "on-primary-container": "#6c4800",
        "on-primary": "#442b00",
        "on-tertiary-fixed": "#141c24",
        "on-surface-variant": "#d6c4ad",
        "inverse-surface": "#dfe2eb",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#005236",
        "surface-bright": "#353940",
        "on-tertiary": "#29313a",
        "on-error-container": "#ffdad6",
        "primary": "#ffd79e",
        "tertiary-fixed-dim": "#bec7d2",
        "tertiary-container": "#b9c2cd",
        "secondary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#ffba47",
        "surface-variant": "#31353c",
        "secondary": "#4edea3",
        "surface": "#10141a",
        "surface-container-low": "#181c22",
        "on-tertiary-container": "#475059",
        "surface-container-lowest": "#0a0e14",
        "on-error": "#690005",
        "secondary-container": "#00a572",
        "on-primary-fixed-variant": "#614000",
        "on-surface": "#dfe2eb",
        "tertiary": "#d5dee9",
        "surface-dim": "#10141a",
        "surface-container-high": "#262a31",
        "outline": "#9f8e79",
        "surface-container": "#1c2026",
        "error": "#ffb4ab",
        "surface-tint": "#ffba47",
        "surface-container-highest": "#31353c",
        "primary-container": "#ffb224",
        "error-container": "#93000a",
        "on-secondary-fixed": "#002113",
        "background": "#10141a",
        "on-tertiary-fixed-variant": "#3f4850",
        "outline-variant": "#514533",
        "inverse-on-surface": "#2d3137",
        "on-secondary": "#003824",
        "on-secondary-container": "#00311f",
        "on-primary-fixed": "#291800",
        "inverse-primary": "#805600"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "unit": "4px",
        "gutter": "24px",
        "container-max": "1200px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "code-sm": ["Geist", "monospace"],
        "geist": ["Geist", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
